// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgaqqbsnhfasgjgfitgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnYXFxYnNuaGZhc2dqZ2ZpdGdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODIyNTQsImV4cCI6MjA3NDQ1ODI1NH0.Yif46_ScacfxwOZLyo5E7kRT_t1dosypBFTnn_id3ms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});